// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// TODO(kimo, 2026-04-05, FIREBASE): Add firebase_core to pubspec.yaml
// and re-run FlutterFire CLI to regenerate this file.
// This file is currently unused — kept as a placeholder for future FCM integration.

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase options for use with your Firebase apps.
///
/// Requires `firebase_core` in pubspec.yaml.
/// Currently not wired into the app — will be used for Push Notifications.
class DefaultFirebaseOptions {
  static Map<String, String> get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const Map<String, String> android = {
    'apiKey': 'AIzaSyAeieJgC9ieJtEeobM2CaihrxdrcX593qc',
    'appId': '1:941281553238:android:943077ad885d21cd2284f7',
    'messagingSenderId': '941281553238',
    'projectId': 'ed-sentre',
    'storageBucket': 'ed-sentre.firebasestorage.app',
  };

  static const Map<String, String> ios = {
    'apiKey': 'AIzaSyC7A-cqil_F5uEKVfe7TYFyfxRcdalVdC4',
    'appId': '1:941281553238:ios:ed18e461060310a82284f7',
    'messagingSenderId': '941281553238',
    'projectId': 'ed-sentre',
    'storageBucket': 'ed-sentre.firebasestorage.app',
    'iosBundleId': 'com.tech.edSentre',
  };
}
